### ISSUE TITLE
Subscribe to app

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#47]
Requires some combination of

- [ ] zaps #39 
- [ ] prepay visualization / method https://github.com/zapstore/zapstore/issues/64
- [ ] proof of missed zaps #61 
- [ ] user receives notification of impending subscription expiration and/or impending subscription renewal https://github.com/zapstore/zapstore/issues/65
- [ ] developer/app can add a lightning address https://github.com/zapstore/zapstore/issues/66
- [ ] user can see and manage their subscriptions https://github.com/zapstore/zapstore/issues/67
- [ ] zapstore % fee https://github.com/zapstore/zapstore/issues/68

### future/unvalidated/undefined

- [ ] recurring subscription NWC (for instance, see mutiny sub) (unclear if there is a practical, working NWC recurring pre-authorized subscription yet)
- [ ] ZS can provide a placeholder LN address on dev's behalf
- [ ] newbie dev can "onboard" to ZS

**Comment by alltheseas** [comment]
@NielLiesmons see damus.io/purple, and https://plus.mutinywallet.com/

**Comment by franzaps** [comment]
Most of this is unclear, archiving for now, see #64
